# Numpy Exercises

In [6]:
import numpy as np

In [25]:
list1 = [1,2,3,4,5]
print(list1)
print(type(list1))

[1, 2, 3, 4, 5]
<class 'list'>


In [26]:
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [8]:
convert_list = np.asarray(list1)
print(convert_list)
print(type(convert_list))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [16]:
arrzeros = np.zeros((2,5))
print(arrzeros)
print(arrzeros.shape)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
(2, 5)


In [17]:
transpose = arrzeros.T
print(transpose)
print(transpose.shape)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
(5, 2)


In [22]:
arr2 = np.arange(10) # [0,10)
print(arr2)
print(type(arr2))
print(arr2.shape)

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
(10,)


In [24]:
arr3 = arr2.reshape(5,2)
print(arr3)
print(arr3.shape)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
(5, 2)


In [28]:
arr4 = np.arange(12).reshape(4,3)
print(arr4)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [42]:
array1 = np.array([[99, 12], [36, 43]])
array2= np.array([[5, 6], [7,8]])
print(array1)

[[99 12]
 [36 43]]


In [43]:
print(array2)

[[5 6]
 [7 8]]


In [44]:
np.concatenate((array1, array2), axis=0)

array([[99, 12],
       [36, 43],
       [ 5,  6],
       [ 7,  8]])

In [45]:
np.concatenate((array1, array2), axis=1)

array([[99, 12,  5,  6],
       [36, 43,  7,  8]])

In [51]:
x = np.arange(5,11) # [5,11) or [5,10]
print(x)

[ 5  6  7  8  9 10]


In [52]:
np.split(x, 3)

[array([5, 6]), array([7, 8]), array([ 9, 10])]

In [55]:
y = np.arange(20).reshape(4,5)
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [56]:
np.delete(y,0,0)

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])